name: Build

on:
  push: # Trigger the workflow on every push event
    branches:
      - '**' # Run on pushes to any branch

# Prevent multiple runs for the same ref from overlapping
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
  setup:
    name: Set Shared Parameters
    runs-on: ubuntu-latest
    outputs:
      jb_bazel_version: ${{ steps.set_params.outputs.jb_bazel_version }}
      jb_bazel_label: ${{ steps.set_params.outputs.jb_bazel_label }}
      bazel_tag: ${{ steps.set_params.outputs.bazel_tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - id: set_params
        run: |
          set -e -x -u -o pipefail
          bazel_tag="$(cat bazel-tag.txt)"
          jb_bazel_version="${bazel_tag}.jb.$(date +%Y%m%d).$GITHUB_RUN_NUMBER"
          echo "jb_bazel_version=$jb_bazel_version" >>"$GITHUB_OUTPUT"
          echo "jb_bazel_label=$jb_bazel_version $(git rev-parse --short HEAD)" >>"$GITHUB_OUTPUT"
          echo "bazel_tag=$bazel_tag" >>"$GITHUB_OUTPUT"

  build:
    name: Build
    runs-on: ${{ matrix.os }}
    needs: setup

    strategy:
      fail-fast: true
      matrix:
        include:
          - os: windows-latest
            exe: .exe
            artifact_os: windows
            artifact_arch: x86_64
            output_user_root: --output_user_root=C:/_bazel_user_root
        # ubuntu-22.04 # reasonable minimum version    
        # os: [ubuntu-22.04, windows-latest]

    steps:
      - name: Print All Environment Variables
        shell: bash
        run: |
          env | sort
          echo ${{ runner.os }}
      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            zip
            unzip
            patch
        if: runner.os == 'Windows'
      - name: Checkout
        uses: actions/checkout@v4
      #  with:
      #    submodules: recursive
      - name: Checkout bazel
        shell: bash
        run: git clone --quiet -b ${{ needs.setup.outputs.bazel_tag }} --depth 1 https://github.com/bazelbuild/bazel.git bazel
      # TODO enable -c opt later    
      # for now only fastbuild
      - name: Build
        run: |
          if [ "${{ runner.os }}" -eq "Windows" ]; then
            export BAZEL_SH=${{ env.MSYS2_PATH }}/usr/bin/bash.exe
          fi
          bazelisk --batch --nohome_rc --nosystem_rc ${{ matrix.output_user_root }} build --verbose_failures -c fastbuild --stamp "--embed_label=${{ needs.setup.outputs.jb_bazel_label }}" //src:bazel${{ matrix.exe }}
        working-directory: ./bazel

      - name: Publish
        uses: actions/upload-artifact@v4
        with:
          name: bazel-${{ needs.setup.outputs.jb_bazel_version }}-${{ matrix.artifact_os }}-${{ matrix.artifact_arch }}${{ matrix.exe }}
      #- name: LS
      #  run: ls -lLR bazel/bazel-bin/
  
# Optional: Add checkout step if you need repo context, though not strictly needed for just printing env vars
#      - name: Check out repository code
#        uses: actions/checkout@v4

#      - name: Print Variables After Checkout (might show slightly different vars)
#        run: env | sort
